### ISSUE TITLE
Galaxy structure

### ISSUE THREAD

**Issue by Tairesh** [Tairesh/SpaceAge#3]
Galaxy is GalaxySize x GalaxySize quadrants. Every Quadrant is N x N Chunks. Every Chunk is an M x M distance units.

## Generation
- Quadrants should be generated when Galaxy is created
- Chunks and stars should be generated when the player is viewing the map

## Tasks
- [ ] Select N (count of chunks in the quadrant), probably 64, so type will be `[Chunk; 4096]`
- [ ] Select M (width of chunk in distance units)
- [ ] Select distance unit (something like a parsec / M)
- [ ] Adjust generator to make galaxies with realistic stars count (now they are too big)
